In [ ]:
%matplotlib inline
import matplotlib.pylab as plt
from matplotlib.pyplot import figure
import numpy as np
from ipywidgets import interact
import sympy as sym
sym.init_printing(True)

# **Python Tutorial**

Python is a popular, high-level, interpreted programming language known for its clear and concise syntax. It supports multiple programming paradigms and is widely used in various fields such as web development, scientific computing, data analysis, and AI. It has a large community of users and developers and is supported by numerous open-source libraries.

<br />

---
this is a **really really basic** python crash course. there is more to learn but we will teach what we need for this project.

**feel free to reach out to the officers if you need any help with python**

you may skip this part if you know python already.

**syntax**

python gets rid of a lot of clutter compared to other langauges.

it relies on proper indentation of 1 tab or 4 spaces for each child code

<br />

*these are right*

```
if(condition):
    print(hello)
```

```
print(hello)
print(world)
```

*these are wrong*

```
if(condition):
      print(hello)
```

```
if(condition):
print(hello)
```

```
  print(hello)
print(world)
```

**dynamic typing**

unlike C/C++, variables can have different types and dont have to be declared with a type and their type can change if a value with different type is assigned. functions can retreieve different variable types as parameters.

In [ ]:
myVar = 10 #int
print(type(myVar))

myVar = 5.5 #float
print(type(myVar))

myVar = "Hello" #string
print(type(myVar))

myVar = [1, 2, 3, 4] #list
print(type(myVar))

myVar = {"name": "John", "age": 30} #dictionary
print(type(myVar))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'list'>
<class 'dict'>


**basic math**

basic math in python follows PEMDAS in most cases.

exponent is `base ** exponent`

multiplication is `a * b`

division is `a / b`

addition is `a + b`

subtraction is `a - b`

if there is same operation precedence in an equation, it will go left to right.

for example, `a * b / c * d`, it will do `a * b` then `/ c` then `* d`

# **Basic NumPy Tutorial**
NumPy is a Python library for numerical computing that provides support for arrays and matrices. It offers a large collection of high-level mathematical functions to operate on these arrays and matrices. It is widely used in data science and scientific computing, as well as for creating and manipulating large, multi-dimensional arrays and matrices.

<br />

---

this is a **really really basic** numpy crash course.

**feel free to reach out to the officers if you need any help with numpy**

numpy will have the prefix `np.` on this project.

you may skip this part if you know numpy already.


**numpy constants**

numpy has constants such as `np.pi` for π which we can call

all numpy constants can be viewed [here](https://bit.ly/np_const)

In [ ]:
print(f'numpy pi: {np.pi}')

numpy pi: 3.141592653589793


**math functions**

numpy has math functions that can be useful for calculations

all numpy math functions can be viewed [here](https://bit.ly/np_math)

In [ ]:
sine = np.sin(np.pi / 2)
d2r = np.deg2rad(30)
r2d = np.rad2deg(np.pi)
print(f'numpy sine: {sine}')
print(f'numpy deg to rads: {d2r}')
print(f'numpy rads to deg: {r2d}')

numpy sine: 1.0
numpy deg to rads: 0.5235987755982988
numpy rads to deg: 180.0


**matrices in numpy**

We can create matrices in numpy.

\begin{bmatrix}a&b&c\\d&e&f\end{bmatrix}
Matrix of 2x3 dimention can be written in numpy as
```
np.matrix([[a, b, c],
           [d, e, f]])
```



In [ ]:
# this creates a new variable matA and matB with 3x3 matrix
matA = np.matrix([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

matB = np.matrix([[-1, 0, 1],
                  [2, 3, -1],
                  [4, 4, 1]])

# this creates a new variable matC with 3x1 matrix
matC = np.matrix([[3],
                  [1],
                  [0]])

**indexing numpy matrices**

***⚠ index starts from 0 in python!***

to get $n_{ij}$th element from $matrix \ A$, you can use


```
n = matA[i, j]
```

to store $10$ into $n_{ij}$th element from $matrix \ A$, you can use

```
matA[i, j] = 10
```

you can get a sub-matrix of a matrix as

$\begin{bmatrix}a&b&c\\d&e&f\\g&h&i\end{bmatrix} \quad \rightarrow \quad \begin{bmatrix}e&f\\h&i\end{bmatrix}$

```
subMat = matA[1:3, 1:3]
```
matrix[range of rows, range of column]

range = [inclusive lower : exclusive upper ]


In [ ]:
print(matA[0:2])
print(matA[1:3, 1:3]) # try changing the values

[[1 2 3]
 [4 5 6]]
[[5 6]
 [8 9]]


**matrix operations**

you can add, subtract, and mulitply matrices as such


```
# addition
matA + matB

#subtraction
matA - matB

#multiplication
number * matA
matA * matC
```



In [ ]:
print('addition')
print(matA + matB)

print('\nsubtraction')
print(matA - matB)

print('\nmultiplication by constant')
print(5 * matA)

print('\nmatrix multiplication')
print(matA * matC)

addition
[[ 0  2  4]
 [ 6  8  5]
 [11 12 10]]

subtraction
[[2 2 2]
 [2 2 7]
 [3 4 8]]

multiplication by constant
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]

matrix multiplication
[[ 5]
 [17]
 [29]]


you can transpose a matrix by

$A = \begin{bmatrix}a&b&c\end{bmatrix} \quad \textrm{ into } \quad  A^{T} = \begin{bmatrix}a\\b\\c\end{bmatrix}$

```
np.matrix([a, b, c]).T
```



In [ ]:
matCT = matC.T
print('matrix transpose')
print(matCT)

matrix transpose
[[3 1 0]]


**matrix concatenation**

you can concat (join) matrices by

$\begin{bmatrix}a&b&c\\d&e&f\end{bmatrix} \quad \textrm{concat with} \quad  \begin{bmatrix}g&h&i\\j&k&l\end{bmatrix} = \begin{bmatrix}a&b&c\\d&e&f\\g&h&i\\j&k&l\end{bmatrix}$



```
np.concatenate((matA, matB, ..., matN))
```




In [ ]:
conMat = np.concatenate((matA, matB))
print('matrix concatenation')
print(conMat)

matrix concatenation
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [-1  0  1]
 [ 2  3 -1]
 [ 4  4  1]]


you can also concat in a different direction by

$\begin{bmatrix}a&b&c\\d&e&f\end{bmatrix} \quad \textrm{concat with} \quad \begin{bmatrix}g&h&i\\j&k&l\end{bmatrix} = \begin{bmatrix}a&b&c&g&h&i\\d&e&f&j&k&l\end{bmatrix}$

```
np.concatenate((matA, matB, ..., matN), axis=1)
```

In [ ]:
conMat = np.concatenate((matA, matB), axis=1)
print('matrix concatenation on axis 1')
print(conMat)

matrix concatenation on axis 1
[[ 1  2  3 -1  0  1]
 [ 4  5  6  2  3 -1]
 [ 7  8  9  4  4  1]]


# **Robotic Arm Exercise #1**

#### Note: There are 2 versions - one uses matricies and one that doesn't. If you're not comfortable using matricies yet, then complete the non-matrix version. However, if you'd like to challenge yourself, complete the matrix version.

<br>

#### **If you complete the non-matrix version before we move, try completing the matrix version!**

<br>

(Correct answers are below this exercise, but only look at them when you're done with your solution)

### <u>**One Arm Non-Matrix Version**</u>

In [ ]:
"""
Template version for 1 arm non-matricies version
"""

# Figure size
plt.rcParams['figure.figsize'] = [16, 8]

def plotXY(x, y):
    # Plots x = xVal, y = yVal    so an uncolored circle for (xVal, yVal)
    plt.scatter(x, y, s=200, facecolors='none', edgecolors='r')
    # Plots a colored circle at origin
    plt.scatter(0, 0, s=200, facecolors='r', edgecolors='r')
    plt.plot([0, x], [0, y])
    plt.axis('square')
    plt.xlim([-5.5,5.5])
    plt.ylim([-5.5,5.5])
    return([ x, y ])

def Robot_Simulator(angle=0):
    # ** YOUR CODE HERE **

    # Convert input angle (degrees) to radians
    # a_radians = angle ... * CODE *
    length = 4

    # X/Y position of the robotic arm end point
    # x = * CODE function of angle *
    # y = * CODE function of angle *

    return plotXY(x, y)

p = interact(Robot_Simulator, angle=(-180,180,2))

interactive(children=(IntSlider(value=0, description='angle', max=180, min=-180, step=2), Output()), _dom_clas…

### <u>**One Arm Matrix Version**</u>

In [ ]:
"""
Template for 1 arm matricies version
"""

# Figure size
plt.rcParams['figure.figsize'] = [16, 8]

def plotMatrix(p):
    # Plots x = xVal, y = yVal    so an uncolored circle for (xVal, yVal)
    plt.scatter(p[0,:].tolist()[0][0],p[1,:].tolist()[0][0], s=200, facecolors='none', edgecolors='r')
    # Plots a colored circle at origin
    plt.scatter(0,0, s=200, facecolors='r', edgecolors='r')
    plt.plot(p[0,:].tolist()[0],p[1,:].tolist()[0])
    plt.axis('square')
    plt.xlim([-5.5,5.5])
    plt.ylim([-5.5,5.5])

def Robot_Simulator(angle=0):
    # Convert to radians
    a_radians = angle * np.pi / 180

    # d is a 1x2 matrix that represents initial arm position [[0], [x0]]
    # d = ...

    # R1 is a 2x2 matrix containing rotation angles
    # R1 = ...

    # Feel free to add print() statements to see what the output of your variables are

    # R1 * d should output a [[x], [y]]
    p = np.concatenate( ( R1 * d, np.matrix([0,0]).T), axis=1 )
    # output should be in the form: [[x, 0], [y, 0]]   (2x2 matrix)
    return plotMatrix(p)

p = interact(Robot_Simulator, angle=(-180,180,2))

interactive(children=(IntSlider(value=0, description='angle', max=180, min=-180, step=2), Output()), _dom_clas…


---


## **Correct Answers:**

---



In [ ]:
#@title Correct Answer for 1 arm non-matricies version { display-mode: "form" }
"""
Correct Answer for 1 arm non-matricies version
"""

# Figure size
plt.rcParams['figure.figsize'] = [16, 8]

def plotXY(x, y):
    # Plots x = xVal, y = yVal    so an uncolored circle for (xVal, yVal)
    plt.scatter(x, y, s=200, facecolors='none', edgecolors='r')
    # Plots a colored circle at origin
    plt.scatter(0, 0, s=200, facecolors='r', edgecolors='r')
    plt.plot([0, x], [0, y])
    plt.axis('square')
    plt.xlim([-5.5,5.5])
    plt.ylim([-5.5,5.5])

def Robot_Simulator(angle=0):
    a_radians = angle/180  * np.pi
    length = 4

    x = length * np.cos(a_radians)
    y = length * np.sin(a_radians)

    return plotXY(x, y)

p = interact(Robot_Simulator, angle=(-180,180,2))

NameError: ignored

In [ ]:
#@title Correct Answer for 1 arm matricies version { display-mode: "form" }
"""
Correct Answer for 1 arm matricies version
"""

# Figure size
plt.rcParams['figure.figsize'] = [16, 8]

def plotMatrix(p):
    # Plots x = xVal, y = yVal    so an uncolored circle for (xVal, yVal)
    plt.scatter(p[0,:].tolist()[0][0],p[1,:].tolist()[0][0], s=200, facecolors='none', edgecolors='r')
    # Plots a colored circle at origin
    plt.scatter(0,0, s=200, facecolors='r', edgecolors='r')
    plt.plot(p[0,:].tolist()[0],p[1,:].tolist()[0])
    plt.axis('square')
    plt.xlim([-5.5,5.5])
    plt.ylim([-5.5,5.5])

def Robot_Simulator(angle=0):
    a_radians = angle/180  * np.pi
    d = np.matrix([0,4]).T
    # d = np.matrix([[0], [4]])
    R1 = np.matrix([[np.cos(a_radians), -np.sin(a_radians)],
                    [np.sin(a_radians),  np.cos(a_radians)]])

    p = np.concatenate( ( R1*d, np.matrix([0,0]).T), axis=1 )
    return plotMatrix(p)

p = interact(Robot_Simulator, angle=(-180,180,2))

# **Robotic Arm Exercise #2 - Second Arm**

#### Note: There are 2 versions - one uses matricies and one that doesn't. If you're not comfortable using matricies yet, then complete the non-matrix version. However, if you'd like to challenge yourself, complete the matrix version.

<br>

#### **If you complete the non-matrix version before we move, try completing the matrix version!**

<br>

(Correct answers are below this exercise, but only look at them when you're done with your solution)

In [ ]:
"""
Template for the 2 arm non-matrix version
"""

from ipywidgets import interact

# Figure size
plt.rcParams['figure.figsize'] = [16, 8]

def plotMatrix(p):
    # Plots x = xVal, y = yVal    so an uncolored circle for (xVal, yVal)
    plt.scatter(p[0,:].tolist()[0],p[1,:].tolist()[0], s=30, facecolors='none', edgecolors='r')
    plt.scatter(0,0, s=30, facecolors='r', edgecolors='r')
    plt.plot(p[0,:].tolist()[0],p[1,:].tolist()[0])
    plt.axis('scaled')
    plt.xlim([-10,10])
    plt.ylim([-10,10])

def Robot_Simulator(a1, a2):
    a1_radians = a1/180  * np.pi
    a2_radians = a2/180  * np.pi

    # Arms Length
    d1 = np.matrix([0,4]).T
    d2 = np.matrix([0,4]).T

    # Base arm - basically the same thing we did in previous exercises
    # x1 = ...
    # y1 = ...

    # Upper arm
    # x2 = ...
    # y2 = ...

    results = np.array([[x1, y1], [x2, y2]])
    p = np.concatenate( (results, np.matrix([0,0]).T), axis=1 )
    return plotMatrix(p)

target = interact(Robot_Simulator, a1=(-180,180), a2=(-180,180))

interactive(children=(IntSlider(value=0, description='a1', max=180, min=-180), IntSlider(value=0, description=…

In [ ]:
"""
Template for the 2 arm matrix version
"""

from ipywidgets import interact

# Figure size
plt.rcParams['figure.figsize'] = [16, 8]

def plotMatrix(p):
    # Plots x = xVal, y = yVal    so an uncolored circle for (xVal, yVal)
    plt.scatter(p[0,:].tolist()[0],p[1,:].tolist()[0], s=30, facecolors='none', edgecolors='r')
    plt.scatter(0,0, s=30, facecolors='r', edgecolors='r')
    plt.plot(p[0,:].tolist()[0],p[1,:].tolist()[0])
    plt.axis('scaled')
    plt.xlim([-10,10])
    plt.ylim([-10,10])

def Robot_Simulator(a1, a2):
    a1_radians = a1/180  * np.pi
    a2_radians = a2/180  * np.pi

    # Arms Initial position
    d1 = np.matrix([0,4]).T
    d2 = np.matrix([0,4]).T

    # Rotation Matricies (2x2 matrix with angle transformations)
    # R2 = ...
    # R1 = ...

    # L1 should be in the form: [[x1], [y1]]
    # L2 should be in the form: [[x2], [x2]]

    # Resulting Positions:
    # L1 = ...
    # L2 = ...


    p = np.concatenate( (L2, L1, np.matrix([0,0]).T), axis=1 )
    return plotMatrix(p)

target = interact(Robot_Simulator, a1=(-180,180), a2=(-180,180))

interactive(children=(IntSlider(value=0, description='a1', max=180, min=-180), IntSlider(value=0, description=…


---


## **Correct Answers:**

---



In [ ]:
#@title Correct answers for the 2 arm non-matrix version
"""
Correct answers for the 2 arm non-matrix version
"""

from ipywidgets import interact

# Figure size
plt.rcParams['figure.figsize'] = [16, 8]

def plotMatrix(p):
    # Plots x = xVal, y = yVal    so an uncolored circle for (xVal, yVal)
    plt.scatter(p[0,:].tolist()[0],p[1,:].tolist()[0], s=30, facecolors='none', edgecolors='r')
    plt.scatter(0,0, s=30, facecolors='r', edgecolors='r')
    plt.plot(p[0,:].tolist()[0],p[1,:].tolist()[0])
    #plt.axis('scaled')
    plt.xlim([-10,10])
    plt.ylim([-10,10])

def Robot_Simulator(a1, a2):
    a1_radians = a1/180  * np.pi
    a2_radians = a2/180  * np.pi

    # Arms Length
    d1 = 4
    d2 = 4

    x1 = 4 * np.sin(a1_radians)
    y1 = 4 * np.cos(a1_radians)

    x2 = 4 * np.sin(a2_radians + a1_radians) + x1
    y2 = 4 * np.cos(a2_radians + a1_radians) + y1

    results = np.array([[x2, x1], [y2, y1]])
    p = np.concatenate( (results, np.matrix([0,0]).T), axis=1 )

    return plotMatrix(p)

target = interact(Robot_Simulator, a1=(-180,180), a2=(-180,180))

interactive(children=(IntSlider(value=0, description='a1', max=180, min=-180), IntSlider(value=0, description=…

In [ ]:
#@title **Correct Answer for 2 arm matricies version** { display-mode: "form" }

"""
Correct answer for the 2 arm version
"""

from ipywidgets import interact

# Figure size
plt.rcParams['figure.figsize'] = [16, 8]

def plotMatrix(p):
    # Plots x = xVal, y = yVal    so an uncolored circle for (xVal, yVal)
    plt.scatter(p[0,:].tolist()[0],p[1,:].tolist()[0], s=30, facecolors='none', edgecolors='r')
    plt.scatter(0,0, s=30, facecolors='r', edgecolors='r')
    plt.plot(p[0,:].tolist()[0],p[1,:].tolist()[0])
    plt.axis('scaled')
    plt.xlim([-10,10])
    plt.ylim([-10,10])

    #return

def Robot_Simulator(a1, a2):
    a1_radians = a1/180  * np.pi
    a2_radians = a2/180  * np.pi

    # Arms Initial position
    d1 = np.matrix([0,4]).T
    d2 = np.matrix([0,4]).T

    # Rotation Matricies
    R1 = np.matrix([[np.cos(a1_radians), -np.sin(a1_radians)],
                    [np.sin(a1_radians),  np.cos(a1_radians)]])
    # Rotate R2 by R1
    R2 = R1 * np.matrix([[np.cos(a2_radians), -np.sin(a2_radians)],
                         [np.sin(a2_radians),  np.cos(a2_radians)]])

    # Resulting Positions:

    # L1 is the lower arm location
    L1 = R1 * d1
    # L2 is the upper arm location
    L2 = R2 * d2 + L1

    p = np.concatenate( (L2, L1, np.matrix([0,0]).T), axis=1 )
    return plotMatrix(p)

target = interact(Robot_Simulator, a1=(-180,180), a2=(-180,180))

interactive(children=(IntSlider(value=0, description='a1', max=180, min=-180), IntSlider(value=0, description=…

In [ ]:
#@title **Bonus: Code for 2 arm version w/ end effector** { display-mode: "form" }

"""
Correct answer for the 2 arm version with end effector
"""

from ipywidgets import interact

def plotMatrix(p):
    # Plots x = xVal, y = yVal    so an uncolored circle for (xVal, yVal)
    plt.scatter(p[0,:].tolist()[0],p[1,:].tolist()[0], s=30, facecolors='none', edgecolors='r')
    plt.scatter(0,0, s=30, facecolors='r', edgecolors='r')
    plt.plot(p[0,:].tolist()[0],p[1,:].tolist()[0])
    plt.axis('scaled')
    plt.xlim([-12,12])
    plt.ylim([-2,12])

    return

def Robot_Simulator(a1, a2, a_ee):
    a1_radians = a1/180  * np.pi
    a2_radians = a2/180  * np.pi
    a_ee_rad = a_ee/180 * np.pi

    # Arms Initial position
    d1 = np.matrix([0,4]).T
    d2 = np.matrix([0,4]).T
    ee = np.matrix([[0, 0], [-1, 0], [-1, 2], [0, 0], [1, 0], [1, 2], [0, 0]]).T


    # Rotation Matricies
    R1 = np.matrix([[np.cos(a1_radians), -np.sin(a1_radians)],
                    [np.sin(a1_radians),  np.cos(a1_radians)]])

    R2 = R1 * np.matrix([[np.cos(a2_radians), -np.sin(a2_radians)],
                    [np.sin(a2_radians),  np.cos(a2_radians)]])

    R_ee = R1 * R2 * np.matrix([[np.cos(a_ee_rad), -np.sin(a_ee_rad)],
                    [np.sin(a_ee_rad),  np.cos(a_ee_rad)]])



    # Resulting
    L1 = R1 * d1

    L2 = R2 * d2 + L1

    L_ee = R_ee * ee + L2

    p = np.concatenate( (L_ee, L2, L1, np.matrix([0,0]).T), axis=1 )
    return plotMatrix(p)

target = interact(Robot_Simulator, a1=(-90,90), a2=(-90,90), a_ee=(-90, 90))

interactive(children=(IntSlider(value=0, description='a1', max=90, min=-90), IntSlider(value=0, description='a…